module Map
  module SmolenskData
    FOREST_HEXES = %w[
      0112 0113 0117
      0202 0203 0212 0213 0217 0218 0224
      0309 0312 0326
      0405 0406 0408 0409 0417 0422 0426 0427
      0505 0506 0507 0509 0512 0514 0515 0517 0518 0527 0528
      0606 0617 0628
      0710 0810 0816 0817 0917
      0721 0722 0723 0822 0823 0924
      0728 0729 0828 0829 0927 0929 0930 1027 1029 1129 1228 1229 1329 1330 1429
      0801 0901 0902
      1601 1611 1701 1702 1706 1707 1711 1712 1801 1806 1808 1810 1901 1902 1906 1907 1908 1909 1911
      2001 2002 2005 2006 2008 2010 2011 2101 2102 2103 2105 2110 2111 2201 2202 2203 2205 2206 2207 2208 2209 2210
      2301 2302 2303 2304 2305 2306 2308 2309 2310 2401 2402 2403 2404 2409 2501 2502 2503 2504 2601 2602 2603 2701 2702
      2002 2102 2103 2202 2203 2302 2303 2304 2402 2403 2404 2503 2504 2603 2703 2704 2705 2801 2802 2803 2901 2902 3001 3101
      2805
      2505 2506 2606 2607 2608 2706 2707 2708 2709 2806 2807 2808
      3002 3003 3103 3104 3203 3302 3304 3403 3503 3602 3603 3703 3705 3802
      3404 3504
      1009 1010 1014 1109 1110 1111 1116 1118 1208 1209 1210 1216 1218
      1104 1105 1106 1203 1204 1205 1206 1304 1305
    ].freeze

    TERRAIN_OVERRIDES = {
      "0412" => "major_city",
      "0513" => "major_city",
      "0420" => "minor_city",
      "0424" => "major_city",
      "0525" => "major_city",
      "1427" => "minor_city",
      "1524" => "minor_city",
      "2216" => "major_city",
      "2217" => "major_city",
      "2626" => "minor_city",
      "3005" => "minor_city",
      "0802" => "swamp",
      "0716" => "swamp",
      "0708" => "swamp",
      "0808" => "swamp",
      "1006" => "swamp",
      "1107" => "swamp",
      "1310" => "swamp",
      "1512" => "swamp",
      "1612" => "swamp",
      "1613" => "swamp",
      "1804" => "swamp",
      "1805" => "swamp",
      "1905" => "swamp",
      "2604" => "swamp",
      "2804" => "swamp",
      "2904" => "swamp",
      "2905" => "swamp",
      "2903" => "swamp",
      "2605" => "swamp",
      "3004" => "swamp",
      "3102" => "swamp",
      "3201" => "swamp",
      "0615" => "swamp"
    }.freeze

    ROAD_EXITS = {
      "0501" => %w[northwest southeast],
      "0601" => %w[northwest southeast],
      "0702" => %w[northwest south],
      "0703" => %w[north south],
      "0704" => %w[north south],
      "0705" => %w[north south],
      "0706" => %w[north northeast],
      "0805" => %w[southwest southeast],
      "0906" => %w[northwest southeast],
      "1006" => %w[northwest southeast],
      "1107" => %w[northwest southeast],
      "1207" => %w[northwest southeast],
      "1308" => %w[northwest southeast],
      "1408" => %w[northwest],
      "0120" => %w[northwest northeast],
      "0219" => %w[southwest northeast],
      "0319" => %w[southwest northeast],
      "0418" => %w[southwest northeast],
      "0518" => %w[north southwest northeast],
      "0517" => %w[north south],
      "0516" => %w[north south],
      "0515" => %w[north south],
      "0514" => %w[north south],
      "0513" => %w[south northeast],
      "0612" => %w[southwest northeast],
      "0712" => %w[southwest northeast],
      "0811" => %w[southwest],
      "0617" => %w[southwest southeast],
      "0718" => %w[northwest northeast],
      "0817" => %w[southwest northeast],
      "0917" => %w[southwest northeast],
      "1016" => %w[southwest northeast],
      "0911" => %w[northeast],
      "1010" => %w[southwest northeast],
      "1110" => %w[southwest northeast],
      "1116" => %w[southwest southeast],
      "1216" => %w[northwest northeast],
      "1209" => %w[southwest northeast],
      "1316" => %w[southwest southeast],
      "1416" => %w[northwest northeast],
      "1309" => %w[southwest southeast],
      "1409" => %w[northwest northeast],
      "1509" => %w[southwest],
      "1516" => %w[southwest northeast],
      "1615" => %w[southwest southeast],
      "1716" => %w[northwest northeast],
      "1815" => %w[southwest northeast],
      "1915" => %w[southwest northeast],
      "2014" => %w[southwest southeast],
      "2115" => %w[northwest northeast],
      "2214" => %w[southwest southeast],
      "2315" => %w[northwest northeast],
      "2414" => %w[southwest southeast],
      "2515" => %w[northwest northeast],
      "2614" => %w[southwest southeast],
      "2715" => %w[northwest northeast],
      "2814" => %w[southwest],
      "2626" => %w[north],
      "2625" => %w[south northwest],
      "2525" => %w[southeast north],
      "2524" => %w[south northwest],
      "2423" => %w[southeast north],
      "2422" => %w[south north],
      "2421" => %w[south northwest],
      "2321" => %w[southeast north],
      "2320" => %w[south northwest],
      "2219" => %w[southeast north],
      "2218" => %w[south north],
      "2217" => %w[south]
    }.freeze

    RAILROAD_EXITS = {
      "0112" => %w[southeast],
      "0109" => %w[northwest southeast],
      "0131" => %w[northeast],
      "0209" => %w[northwest south],
      "0210" => %w[north southeast],
      "0212" => %w[northwest northeast],
      "0228" => %w[northeast south],
      "0229" => %w[north south],
      "0230" => %w[southwest north],
      "0311" => %w[northwest southeast],
      "0312" => %w[southwest southeast],
      "0322" => %w[northeast south],
      "0323" => %w[north south],
      "0324" => %w[north south],
      "0325" => %w[north south],
      "0326" => %w[north south],
      "0327" => %w[north south],
      "0328" => %w[southwest north],
      "0411" => %w[northwest south],
      "0412" => %w[northwest north south southeast],
      "0413" => %w[north south],
      "0414" => %w[north south],
      "0415" => %w[north south],
      "0416" => %w[north south],
      "0417" => %w[north south],
      "0418" => %w[north south],
      "0419" => %w[north south northeast],
      "0420" => %w[north south southeast],
      "0421" => %w[north southwest],
      "0525" => %w[southeast],
      "0521" => %w[northwest southeast],
      "0513" => %w[northwest southeast],
      "0625" => %w[northwest northeast],
      "0621" => %w[northwest southeast],
      "0519" => %w[southwest northeast],
      "0613" => %w[northwest southeast],
      "0618" => %w[southwest northeast],
      "0725" => %w[southwest southeast],
      "0722" => %w[northwest southeast],
      "0714" => %w[northwest southeast],
      "0718" => %w[southwest northeast],
      "0825" => %w[northwest northeast],
      "0822" => %w[northwest southeast],
      "0814" => %w[northwest southeast],
      "0817" => %w[southwest northeast],
      "0925" => %w[southwest southeast],
      "0923" => %w[northwest southeast],
      "0915" => %w[northwest southeast],
      "0917" => %w[southwest northeast],
      "1025" => %w[northwest northeast],
      "1023" => %w[northwest south],
      "1024" => %w[north southeast],
      "1015" => %w[northwest],
      "1016" => %w[southwest northeast],
      "1116" => %w[southwest southeast],
      "1125" => %w[southwest northwest southeast],
      "1216" => %w[northwest northeast],
      "1225" => %w[northwest northeast southeast],
      "1325" => %w[southwest northeast],
      "1424" => %w[southwest northeast],
      "1316" => %w[southwest southeast],
      "1326" => %w[northwest south],
      "1327" => %w[north southeast],
      "1416" => %w[northwest northeast],
      "1427" => %w[northwest southeast],
      "1524" => %w[southwest southeast],
      "1624" => %w[northwest southeast],
      "1516" => %w[southwest northeast],
      "1528" => %w[northwest south],
      "1529" => %w[north southeast],
      "1615" => %w[southwest southeast],
      "1629" => %w[northwest southeast],
      "1725" => %w[northwest northeast],
      "1824" => %w[southwest southeast],
      "1925" => %w[northwest southeast],
      "2025" => %w[northwest southeast],
      "2126" => %w[northwest northeast],
      "2225" => %w[southwest southeast],
      "2326" => %w[northwest southeast],
      "2426" => %w[northwest northeast],
      "2526" => %w[southwest southeast],
      "2626" => %w[northwest south],
      "2627" => %w[north southeast],
      "2728" => %w[northwest southeast],
      "2828" => %w[northwest southeast],
      "2929" => %w[northwest southeast],
      "3029" => %w[northwest south],
      "3030" => %w[north southeast],
      "1716" => %w[northwest northeast],
      "1730" => %w[northwest south],
      "1731" => %w[north southeast],
      "1815" => %w[southwest northeast],
      "1831" => %w[northwest],
      "3131" => %w[northwest],
      "1915" => %w[southwest]
    }.freeze

    HEXSIDE_FEATURES = [
      { hex_number: "0112", direction: "south", feature_type: "river" },
      { hex_number: "0113", direction: "northeast", feature_type: "river" },
      { hex_number: "0120", direction: "south", feature_type: "river" },
      { hex_number: "0120", direction: "southeast", feature_type: "river" },
      { hex_number: "0212", direction: "south", feature_type: "river" },
      { hex_number: "0219", direction: "south", feature_type: "river" },
      { hex_number: "0312", direction: "south", feature_type: "river" },
      { hex_number: "0313", direction: "northwest", feature_type: "river" },
      { hex_number: "0313", direction: "northeast", feature_type: "river" },
      { hex_number: "0413", direction: "northeast", feature_type: "river" },
      { hex_number: "0413", direction: "southeast", feature_type: "river" },
      { hex_number: "0414", direction: "northeast", feature_type: "river" },
      { hex_number: "0412", direction: "south", feature_type: "river" },
      { hex_number: "0412", direction: "southeast", feature_type: "river" },
      { hex_number: "0412", direction: "northeast", feature_type: "river" },
      { hex_number: "0411", direction: "southeast", feature_type: "river" },
      { hex_number: "0512", direction: "north", feature_type: "river" },
      { hex_number: "0511", direction: "southeast", feature_type: "river" },
      { hex_number: "0611", direction: "north", feature_type: "river" },
      { hex_number: "0610", direction: "southeast", feature_type: "river" },
      { hex_number: "0710", direction: "south", feature_type: "river" },
      { hex_number: "0711", direction: "northeast", feature_type: "river" },
      { hex_number: "0810", direction: "south", feature_type: "river" },
      { hex_number: "0810", direction: "southeast", feature_type: "river" },
      { hex_number: "0811", direction: "northeast", feature_type: "river" },
      { hex_number: "0911", direction: "south", feature_type: "river" },
      { hex_number: "0912", direction: "northeast", feature_type: "river" },
      { hex_number: "1011", direction: "south", feature_type: "river" },
      { hex_number: "1011", direction: "southeast", feature_type: "river" },
      { hex_number: "1111", direction: "south", feature_type: "river" },
      { hex_number: "1111", direction: "southeast", feature_type: "river" },
      { hex_number: "1210", direction: "south", feature_type: "river" },
      { hex_number: "1211", direction: "northeast", feature_type: "river" },
      { hex_number: "1311", direction: "south", feature_type: "river" },
      { hex_number: "1312", direction: "northeast", feature_type: "river" },
      { hex_number: "1411", direction: "south", feature_type: "river" },
      { hex_number: "1412", direction: "northeast", feature_type: "river" },
      { hex_number: "1512", direction: "south", feature_type: "river" },
      { hex_number: "1512", direction: "southeast", feature_type: "river" },
      { hex_number: "1611", direction: "south", feature_type: "river" },
      { hex_number: "1611", direction: "southeast", feature_type: "river" },
      { hex_number: "1622", direction: "southeast", feature_type: "river" },
      { hex_number: "1623", direction: "south", feature_type: "river" },
      { hex_number: "1623", direction: "northeast", feature_type: "river" },
      { hex_number: "1623", direction: "southeast", feature_type: "river" },
      { hex_number: "1513", direction: "northeast", feature_type: "river" },
      { hex_number: "1513", direction: "southeast", feature_type: "river" },
      { hex_number: "1514", direction: "northeast", feature_type: "river" },
      { hex_number: "1514", direction: "southeast", feature_type: "river" },
      { hex_number: "1722", direction: "south", feature_type: "river" },
      { hex_number: "1722", direction: "southeast", feature_type: "river" },
      { hex_number: "1821", direction: "south", feature_type: "river" },
      { hex_number: "1821", direction: "southeast", feature_type: "river" },
      { hex_number: "1920", direction: "southeast", feature_type: "river" },
      { hex_number: "1921", direction: "south", feature_type: "river" },
      { hex_number: "1921", direction: "northeast", feature_type: "river" },
      { hex_number: "1921", direction: "southeast", feature_type: "river" },
      { hex_number: "0320", direction: "southwest", feature_type: "river" },
      { hex_number: "0320", direction: "south", feature_type: "river" },
      { hex_number: "0325", direction: "southeast", feature_type: "river" },
      { hex_number: "0326", direction: "southeast", feature_type: "river" },
      { hex_number: "0326", direction: "northeast", feature_type: "river" },
      { hex_number: "0327", direction: "southeast", feature_type: "river" },
      { hex_number: "0327", direction: "northeast", feature_type: "river" },
      { hex_number: "0328", direction: "southeast", feature_type: "river" },
      { hex_number: "0328", direction: "northeast", feature_type: "river" },
      { hex_number: "0329", direction: "southeast", feature_type: "river" },
      { hex_number: "0329", direction: "northeast", feature_type: "river" },
      { hex_number: "0330", direction: "southeast", feature_type: "river" },
      { hex_number: "0330", direction: "northeast", feature_type: "river" },
      { hex_number: "0331", direction: "southeast", feature_type: "river" },
      { hex_number: "0331", direction: "northeast", feature_type: "river" },
      { hex_number: "0419", direction: "southeast", feature_type: "river" },
      { hex_number: "0420", direction: "southwest", feature_type: "river" },
      { hex_number: "0420", direction: "south", feature_type: "river" },
      { hex_number: "0420", direction: "southeast", feature_type: "river" },
      { hex_number: "0420", direction: "northeast", feature_type: "river" },
      { hex_number: "0421", direction: "southeast", feature_type: "river" },
      { hex_number: "0421", direction: "northeast", feature_type: "river" },
      { hex_number: "0422", direction: "southeast", feature_type: "river" },
      { hex_number: "0422", direction: "northeast", feature_type: "river" },
      { hex_number: "0423", direction: "southeast", feature_type: "river" },
      { hex_number: "0423", direction: "northeast", feature_type: "river" },
      { hex_number: "0424", direction: "south", feature_type: "river" },
      { hex_number: "0424", direction: "southeast", feature_type: "river" },
      { hex_number: "0424", direction: "northeast", feature_type: "river" },
      { hex_number: "0701", direction: "southeast", feature_type: "river" },
      { hex_number: "0702", direction: "northeast", feature_type: "river" },
      { hex_number: "0801", direction: "south", feature_type: "river" },
      { hex_number: "0802", direction: "northeast", feature_type: "river" },
      { hex_number: "0802", direction: "southeast", feature_type: "river" },
      { hex_number: "0803", direction: "northeast", feature_type: "river" },
      { hex_number: "0803", direction: "southeast", feature_type: "river" },
      { hex_number: "0803", direction: "south", feature_type: "river" },
      { hex_number: "0704", direction: "southeast", feature_type: "river" },
      { hex_number: "0705", direction: "northeast", feature_type: "river" },
      { hex_number: "0705", direction: "southeast", feature_type: "river" },
      { hex_number: "0731", direction: "southeast", feature_type: "river" },
      { hex_number: "0829", direction: "southeast", feature_type: "river" },
      { hex_number: "0830", direction: "northeast", feature_type: "river" },
      { hex_number: "0830", direction: "southeast", feature_type: "river" },
      { hex_number: "0830", direction: "south", feature_type: "river" },
      { hex_number: "1601", direction: "south", feature_type: "river" },
      { hex_number: "1602", direction: "northeast", feature_type: "river" },
      { hex_number: "1702", direction: "south", feature_type: "river" },
      { hex_number: "1602", direction: "southeast", feature_type: "river" },
      { hex_number: "1603", direction: "northeast", feature_type: "river" },
      { hex_number: "1703", direction: "south", feature_type: "river" },
      { hex_number: "1704", direction: "northeast", feature_type: "river" },
      { hex_number: "1704", direction: "southeast", feature_type: "river" },
      { hex_number: "1705", direction: "northeast", feature_type: "river" },
      { hex_number: "1705", direction: "southeast", feature_type: "river" },
      { hex_number: "1706", direction: "northeast", feature_type: "river" },
      { hex_number: "1706", direction: "southeast", feature_type: "river" },
      { hex_number: "1707", direction: "northeast", feature_type: "river" },
      { hex_number: "1707", direction: "south", feature_type: "river" },
      { hex_number: "1707", direction: "southeast", feature_type: "river" },
      { hex_number: "1702", direction: "southeast", feature_type: "river" },
      { hex_number: "1801", direction: "south", feature_type: "river" },
      { hex_number: "1902", direction: "southwest", feature_type: "river" },
      { hex_number: "1902", direction: "south", feature_type: "river" },
      { hex_number: "1902", direction: "southeast", feature_type: "river" },
      { hex_number: "2001", direction: "south", feature_type: "river" },
      { hex_number: "2001", direction: "southeast", feature_type: "river" },
      { hex_number: "2101", direction: "south", feature_type: "river" },
      { hex_number: "2201", direction: "southwest", feature_type: "river" },
      { hex_number: "2201", direction: "south", feature_type: "river" },
      { hex_number: "2201", direction: "southeast", feature_type: "river" },
      { hex_number: "2301", direction: "south", feature_type: "river" },
      { hex_number: "2401", direction: "southwest", feature_type: "river" },
      { hex_number: "2401", direction: "south", feature_type: "river" },
      { hex_number: "2502", direction: "southwest", feature_type: "river" },
      { hex_number: "2502", direction: "south", feature_type: "river" },
      { hex_number: "2602", direction: "southwest", feature_type: "river" },
      { hex_number: "2602", direction: "south", feature_type: "river" },
      { hex_number: "2602", direction: "southeast", feature_type: "river" },
      { hex_number: "2701", direction: "southeast", feature_type: "river" },
      { hex_number: "2702", direction: "northeast", feature_type: "river" },
      { hex_number: "2702", direction: "southeast", feature_type: "river" },
      { hex_number: "2702", direction: "south", feature_type: "river" },
      { hex_number: "1607", direction: "northeast", feature_type: "river" },
      { hex_number: "1606", direction: "south", feature_type: "river" },
      { hex_number: "1507", direction: "southeast", feature_type: "river" },
      { hex_number: "1507", direction: "south", feature_type: "river" },
      { hex_number: "1407", direction: "southeast", feature_type: "river" },
      { hex_number: "1408", direction: "northeast", feature_type: "river" },
      { hex_number: "1408", direction: "southeast", feature_type: "river" },
      { hex_number: "1408", direction: "south", feature_type: "river" },
      { hex_number: "1309", direction: "northeast", feature_type: "river" },
      { hex_number: "1308", direction: "south", feature_type: "river" },
      { hex_number: "1208", direction: "southeast", feature_type: "river" },
      { hex_number: "1208", direction: "south", feature_type: "river" },
      { hex_number: "1109", direction: "southeast", feature_type: "river" },
      { hex_number: "1109", direction: "south", feature_type: "river" },
      { hex_number: "1009", direction: "southeast", feature_type: "river" },
      { hex_number: "1009", direction: "south", feature_type: "river" },
      { hex_number: "0910", direction: "southeast", feature_type: "river" },
      { hex_number: "0910", direction: "south", feature_type: "river" },
      { hex_number: "0929", direction: "south", feature_type: "river" },
      { hex_number: "0929", direction: "southeast", feature_type: "river" },
      { hex_number: "0810", direction: "northeast", feature_type: "river" },
      { hex_number: "0809", direction: "southeast", feature_type: "river" },
      { hex_number: "0909", direction: "south", feature_type: "river" },
      { hex_number: "0909", direction: "southeast", feature_type: "river" },
      { hex_number: "1008", direction: "south", feature_type: "river" },
      { hex_number: "1008", direction: "southeast", feature_type: "river" },
      { hex_number: "1008", direction: "northeast", feature_type: "river" },
      { hex_number: "1028", direction: "south", feature_type: "river" },
      { hex_number: "1028", direction: "southeast", feature_type: "river" },
      { hex_number: "1007", direction: "south", feature_type: "river" },
      { hex_number: "1128", direction: "south", feature_type: "river" },
      { hex_number: "1128", direction: "southeast", feature_type: "river" },
      { hex_number: "1227", direction: "south", feature_type: "river" },
      { hex_number: "1227", direction: "southeast", feature_type: "river" },
      { hex_number: "1327", direction: "south", feature_type: "river" },
      { hex_number: "1327", direction: "southeast", feature_type: "river" },
      { hex_number: "1317", direction: "south", feature_type: "river" },
      { hex_number: "1426", direction: "south", feature_type: "river" },
      { hex_number: "1426", direction: "southeast", feature_type: "river" },
      { hex_number: "1423", direction: "northeast", feature_type: "river" },
      { hex_number: "1422", direction: "southeast", feature_type: "river" },
      { hex_number: "1422", direction: "northeast", feature_type: "river" },
      { hex_number: "1421", direction: "southeast", feature_type: "river" },
      { hex_number: "1520", direction: "southeast", feature_type: "river" },
      { hex_number: "1521", direction: "south", feature_type: "river" },
      { hex_number: "1521", direction: "southeast", feature_type: "river" },
      { hex_number: "1521", direction: "northeast", feature_type: "river" },
      { hex_number: "1524", direction: "north", feature_type: "river" },
      { hex_number: "1524", direction: "northeast", feature_type: "river" },
      { hex_number: "1524", direction: "southeast", feature_type: "river" },
      { hex_number: "1525", direction: "northeast", feature_type: "river" },
      { hex_number: "1525", direction: "southeast", feature_type: "river" },
      { hex_number: "1526", direction: "south", feature_type: "river" },
      { hex_number: "1526", direction: "northeast", feature_type: "river" },
      { hex_number: "1526", direction: "southeast", feature_type: "river" },
      { hex_number: "0520", direction: "north", feature_type: "river" },
      { hex_number: "0619", direction: "northwest", feature_type: "river" },
      { hex_number: "0619", direction: "north", feature_type: "river" },
      { hex_number: "0719", direction: "northwest", feature_type: "river" },
      { hex_number: "0719", direction: "north", feature_type: "river" },
      { hex_number: "0719", direction: "northeast", feature_type: "river" },
      { hex_number: "0819", direction: "north", feature_type: "river" },
      { hex_number: "0919", direction: "northwest", feature_type: "river" },
      { hex_number: "0918", direction: "southwest", feature_type: "river" },
      { hex_number: "0918", direction: "northwest", feature_type: "river" },
      { hex_number: "0918", direction: "north", feature_type: "river" },
      { hex_number: "1017", direction: "northwest", feature_type: "river" },
      { hex_number: "1017", direction: "north", feature_type: "river" },
      { hex_number: "1017", direction: "northeast", feature_type: "river" },
      { hex_number: "1118", direction: "north", feature_type: "river" },
      { hex_number: "1118", direction: "northeast", feature_type: "river" },
      { hex_number: "1218", direction: "north", feature_type: "river" },
      { hex_number: "1318", direction: "northwest", feature_type: "river" },
      { hex_number: "1417", direction: "northwest", feature_type: "river" },
      { hex_number: "1417", direction: "north", feature_type: "river" },
      { hex_number: "1417", direction: "northeast", feature_type: "river" },
      { hex_number: "1518", direction: "north", feature_type: "river" },
      { hex_number: "1617", direction: "northwest", feature_type: "river" },
      { hex_number: "1617", direction: "north", feature_type: "river" },
      { hex_number: "1717", direction: "northwest", feature_type: "river" },
      { hex_number: "1717", direction: "north", feature_type: "river" },
      { hex_number: "1816", direction: "northwest", feature_type: "river" },
      { hex_number: "1816", direction: "north", feature_type: "river" },
      { hex_number: "1916", direction: "northwest", feature_type: "river" },
      { hex_number: "1916", direction: "north", feature_type: "river" },
      { hex_number: "1916", direction: "northeast", feature_type: "river" },
      { hex_number: "2016", direction: "north", feature_type: "river" },
      { hex_number: "2016", direction: "northeast", feature_type: "river" },
      { hex_number: "2117", direction: "north", feature_type: "river" },
      { hex_number: "2117", direction: "northeast", feature_type: "river" },
      { hex_number: "2217", direction: "north", feature_type: "river" },
      { hex_number: "2217", direction: "northeast", feature_type: "river" },
      { hex_number: "2318", direction: "north", feature_type: "river" },
      { hex_number: "2318", direction: "northeast", feature_type: "river" },
      { hex_number: "2318", direction: "southeast", feature_type: "river" },
      { hex_number: "2319", direction: "northeast", feature_type: "river" },
      { hex_number: "2419", direction: "north", feature_type: "river" },
      { hex_number: "2519", direction: "northwest", feature_type: "river" },
      { hex_number: "2518", direction: "southwest", feature_type: "river" },
      { hex_number: "2518", direction: "northwest", feature_type: "river" },
      { hex_number: "2518", direction: "north", feature_type: "river" },
      { hex_number: "2617", direction: "northwest", feature_type: "river" },
      { hex_number: "2617", direction: "north", feature_type: "river" },
      { hex_number: "2717", direction: "northwest", feature_type: "river" },
      { hex_number: "2717", direction: "north", feature_type: "river" },
      { hex_number: "2717", direction: "northeast", feature_type: "river" },
      { hex_number: "2716", direction: "southwest", feature_type: "river" },
      { hex_number: "2716", direction: "northwest", feature_type: "river" },
      { hex_number: "2716", direction: "north", feature_type: "river" },
      { hex_number: "2815", direction: "northwest", feature_type: "river" },
      { hex_number: "2815", direction: "north", feature_type: "river" },
      { hex_number: "2915", direction: "northwest", feature_type: "river" },
      { hex_number: "2914", direction: "southwest", feature_type: "river" },
      { hex_number: "2914", direction: "northwest", feature_type: "river" },
      { hex_number: "2914", direction: "north", feature_type: "river" },
      { hex_number: "3013", direction: "northwest", feature_type: "river" },
      { hex_number: "3012", direction: "southwest", feature_type: "river" },
      { hex_number: "3012", direction: "northwest", feature_type: "river" },
      { hex_number: "3012", direction: "north", feature_type: "river" },
      { hex_number: "3112", direction: "northwest", feature_type: "river" },
      { hex_number: "3111", direction: "southwest", feature_type: "river" },
      { hex_number: "3111", direction: "northwest", feature_type: "river" },
      { hex_number: "3110", direction: "southwest", feature_type: "river" },
      { hex_number: "3110", direction: "northwest", feature_type: "river" },
      { hex_number: "1806", direction: "north", feature_type: "river" },
      { hex_number: "1906", direction: "northwest", feature_type: "river" },
      { hex_number: "1906", direction: "north", feature_type: "river" },
      { hex_number: "2005", direction: "northwest", feature_type: "river" },
      { hex_number: "2004", direction: "southwest", feature_type: "river" },
      { hex_number: "2004", direction: "northwest", feature_type: "river" },
      { hex_number: "2004", direction: "north", feature_type: "river" },
      { hex_number: "2104", direction: "northwest", feature_type: "river" },
      { hex_number: "2104", direction: "north", feature_type: "river" },
      { hex_number: "2104", direction: "northeast", feature_type: "river" },
      { hex_number: "2204", direction: "north", feature_type: "river" },
      { hex_number: "2204", direction: "northeast", feature_type: "river" },
      { hex_number: "2305", direction: "north", feature_type: "river" },
      { hex_number: "2305", direction: "northeast", feature_type: "river" },
      { hex_number: "2405", direction: "north", feature_type: "river" },
      { hex_number: "2505", direction: "northwest", feature_type: "river" },
      { hex_number: "2505", direction: "north", feature_type: "river" },
      { hex_number: "2505", direction: "northeast", feature_type: "river" },
      { hex_number: "2605", direction: "north", feature_type: "river" },
      { hex_number: "2605", direction: "northeast", feature_type: "river" },
      { hex_number: "2706", direction: "north", feature_type: "river" },
      { hex_number: "2805", direction: "northwest", feature_type: "river" },
      { hex_number: "2805", direction: "north", feature_type: "river" },
      { hex_number: "2905", direction: "northwest", feature_type: "river" },
      { hex_number: "2905", direction: "north", feature_type: "river" },
      { hex_number: "2904", direction: "southwest", feature_type: "river" },
      { hex_number: "2904", direction: "northwest", feature_type: "river" },
      { hex_number: "2904", direction: "north", feature_type: "river" },
      { hex_number: "3003", direction: "northwest", feature_type: "river" },
      { hex_number: "3002", direction: "southwest", feature_type: "river" },
      { hex_number: "3002", direction: "northwest", feature_type: "river" },
      { hex_number: "3002", direction: "north", feature_type: "river" },
      { hex_number: "3102", direction: "northwest", feature_type: "river" },
      { hex_number: "3102", direction: "north", feature_type: "river" },
      { hex_number: "3004", direction: "northwest", feature_type: "river" },
      { hex_number: "3004", direction: "north", feature_type: "river" },
      { hex_number: "3004", direction: "northeast", feature_type: "river" },
      { hex_number: "3105", direction: "north", feature_type: "river" },
      { hex_number: "3204", direction: "northwest", feature_type: "river" },
      { hex_number: "3204", direction: "north", feature_type: "river" },
      { hex_number: "3204", direction: "northeast", feature_type: "river" },
      { hex_number: "3305", direction: "north", feature_type: "river" },
      { hex_number: "3404", direction: "northwest", feature_type: "river" },
      { hex_number: "3404", direction: "north", feature_type: "river" },
      { hex_number: "3504", direction: "northwest", feature_type: "river" },
      { hex_number: "3504", direction: "north", feature_type: "river" },
      { hex_number: "3603", direction: "northwest", feature_type: "river" },
      { hex_number: "3603", direction: "north", feature_type: "river" },
      { hex_number: "1931", direction: "southwest", feature_type: "river" },
      { hex_number: "1931", direction: "northwest", feature_type: "river" },
      { hex_number: "1830", direction: "northeast", feature_type: "river" },
      { hex_number: "1930", direction: "northwest", feature_type: "river" },
      { hex_number: "1930", direction: "north", feature_type: "river" },
      { hex_number: "1930", direction: "northeast", feature_type: "river" },
      { hex_number: "2030", direction: "north", feature_type: "river" },
      { hex_number: "2030", direction: "northeast", feature_type: "river" },
      { hex_number: "2131", direction: "north", feature_type: "river" },
      { hex_number: "2230", direction: "northwest", feature_type: "river" },
      { hex_number: "2229", direction: "southwest", feature_type: "river" },
      { hex_number: "2229", direction: "northwest", feature_type: "river" },
      { hex_number: "2228", direction: "southwest", feature_type: "river" },
      { hex_number: "2228", direction: "northwest", feature_type: "river" },
      { hex_number: "2228", direction: "north", feature_type: "river" },
      { hex_number: "2328", direction: "northwest", feature_type: "river" },
      { hex_number: "2327", direction: "southwest", feature_type: "river" },
      { hex_number: "2327", direction: "northwest", feature_type: "river" },
      { hex_number: "2327", direction: "north", feature_type: "river" },
      { hex_number: "2327", direction: "northeast", feature_type: "river" },
      { hex_number: "2427", direction: "north", feature_type: "river" },
      { hex_number: "2427", direction: "northeast", feature_type: "river" },
      { hex_number: "2528", direction: "north", feature_type: "river" },
      { hex_number: "2528", direction: "northeast", feature_type: "river" },
      { hex_number: "2528", direction: "southeast", feature_type: "river" },
      { hex_number: "2529", direction: "northeast", feature_type: "river" },
      { hex_number: "2629", direction: "north", feature_type: "river" },
      { hex_number: "2629", direction: "northeast", feature_type: "river" },
      { hex_number: "2730", direction: "north", feature_type: "river" },
      { hex_number: "2730", direction: "northeast", feature_type: "river" },
      { hex_number: "2730", direction: "southeast", feature_type: "river" },
      { hex_number: "2730", direction: "south", feature_type: "river" },
      { hex_number: "2630", direction: "southeast", feature_type: "river" },
      { hex_number: "2630", direction: "south", feature_type: "river" },
      { hex_number: "2531", direction: "southeast", feature_type: "river" },
      { hex_number: "2627", direction: "south", feature_type: "river" },
      { hex_number: "2627", direction: "southeast", feature_type: "river" },
      { hex_number: "2627", direction: "northeast", feature_type: "river" },
      { hex_number: "2626", direction: "southeast", feature_type: "river" },
      { hex_number: "2626", direction: "northeast", feature_type: "river" },
      { hex_number: "2625", direction: "southeast", feature_type: "river" },
      { hex_number: "2625", direction: "northeast", feature_type: "river" },
      { hex_number: "2624", direction: "southeast", feature_type: "river" },
      { hex_number: "0908", direction: "northeast", feature_type: "river" },
      { hex_number: "0907", direction: "southeast", feature_type: "river" },
      { hex_number: "0602", direction: "north", feature_type: "lake" },
      { hex_number: "0602", direction: "northeast", feature_type: "lake" },
      { hex_number: "0602", direction: "southeast", feature_type: "lake" },
      { hex_number: "0602", direction: "south", feature_type: "lake" },
      { hex_number: "0602", direction: "southwest", feature_type: "lake" },
      { hex_number: "0602", direction: "northwest", feature_type: "lake" },
      { hex_number: "0907", direction: "northeast", feature_type: "lake" },
      { hex_number: "1502", direction: "north", feature_type: "lake" },
      { hex_number: "1502", direction: "northeast", feature_type: "lake" },
      { hex_number: "1502", direction: "southeast", feature_type: "lake" },
      { hex_number: "1502", direction: "south", feature_type: "lake" },
      { hex_number: "1502", direction: "southwest", feature_type: "lake" },
      { hex_number: "1502", direction: "northwest", feature_type: "lake" }
    ].freeze

    class << self
      def apply!
        apply_terrain_overrides!
        apply_route_overrides!
        apply_hexside_features!
      end

      private

      def apply_terrain_overrides!
        Hex.where(hex_number: FOREST_HEXES).update_all(terrain_type: "forest")

        TERRAIN_OVERRIDES.each do |hex_number, terrain_type|
          Hex.find_by!(hex_number: hex_number).update!(terrain_type:)
        end
      end

      def apply_route_overrides!
        ROAD_EXITS.each do |hex_number, directions|
          Hex.find_by!(hex_number: hex_number).update!(road_exits: directions)
        end

        RAILROAD_EXITS.each do |hex_number, directions|
          Hex.find_by!(hex_number: hex_number).update!(railroad_exits: directions)
        end
      end

      def apply_hexside_features!
        HexsideFeature.delete_all

        HEXSIDE_FEATURES.each do |feature|
          HexsideFeature.create!(
            hex: Hex.find_by!(hex_number: feature.fetch(:hex_number)),
            direction: feature.fetch(:direction),
            feature_type: feature.fetch(:feature_type)
          )
        end
      end

    end
  end
end
